"""
Code Template Indexer — indexes project scaffolds, React apps, API boilerplates,
and website templates into the workflow database for RAG search.

Run: python -m app.services.template_indexer [--db workflows.db]
"""

import sqlite3
import os
import sys
from pathlib import Path

DB_PATH = os.getenv("WORKFLOW_DB_PATH", str(Path(__file__).parent.parent.parent / "workflows.db"))

TEMPLATES = [
    # ── React / Frontend ──
    {
        "name": "React + Vite SPA",
        "category": "Frontend",
        "subcategory": "React",
        "tech_stack": "React, Vite, TypeScript, Tailwind CSS, React Router",
        "description": "Single-page application with Vite bundler, TypeScript, Tailwind CSS styling, and client-side routing. Includes ESLint, component structure, and hot reload.",
        "folder_structure": "src/components, src/pages, src/hooks, src/lib, src/assets, public",
        "key_files": "vite.config.ts, src/App.tsx, src/main.tsx, src/index.css, tailwind.config.js, tsconfig.json",
        "dependencies": "react, react-dom, react-router-dom, tailwindcss, typescript, vite, @vitejs/plugin-react",
        "patterns": "component composition, custom hooks, context providers, lazy loading, error boundaries",
        "use_cases": "dashboards, admin panels, internal tools, data visualization apps, form-heavy apps",
        "complexity": "medium",
    },
    {
        "name": "Next.js Full-Stack App",
        "category": "Frontend",
        "subcategory": "Next.js",
        "tech_stack": "Next.js, TypeScript, Tailwind CSS, App Router, Server Components",
        "description": "Full-stack Next.js application with App Router, server and client components, API routes, middleware, and SSR/SSG support. Includes auth patterns and database integration.",
        "folder_structure": "app/(routes), app/api, components, lib, public, middleware.ts",
        "key_files": "next.config.ts, app/layout.tsx, app/page.tsx, middleware.ts, tailwind.config.ts, .env.local",
        "dependencies": "next, react, react-dom, tailwindcss, typescript, @types/react",
        "patterns": "server components, streaming SSR, parallel routes, intercepting routes, server actions, middleware auth",
        "use_cases": "marketing sites, SaaS apps, e-commerce, blogs, portfolio sites, landing pages",
        "complexity": "medium",
    },
    {
        "name": "React Native Mobile App",
        "category": "Mobile",
        "subcategory": "React Native",
        "tech_stack": "React Native, Expo, TypeScript, React Navigation, AsyncStorage",
        "description": "Cross-platform mobile application with Expo managed workflow, tab/stack navigation, local storage, push notifications, and native device API access.",
        "folder_structure": "app/(tabs), components, hooks, constants, assets, scripts",
        "key_files": "app.json, app/(tabs)/index.tsx, app/_layout.tsx, babel.config.js, tsconfig.json",
        "dependencies": "expo, react-native, react-navigation, expo-router, expo-notifications, async-storage",
        "patterns": "tab navigation, stack navigation, deep linking, offline-first, push notifications, gesture handling",
        "use_cases": "consumer apps, delivery apps, social apps, fitness trackers, marketplace apps",
        "complexity": "high",
    },
    {
        "name": "Vue 3 + Nuxt Full-Stack",
        "category": "Frontend",
        "subcategory": "Vue",
        "tech_stack": "Vue 3, Nuxt 3, TypeScript, Pinia, Tailwind CSS, Nitro",
        "description": "Full-stack Vue 3 application with Nuxt 3 framework, Composition API, Pinia state management, server routes via Nitro, and auto-imports.",
        "folder_structure": "pages, components, composables, server/api, layouts, plugins, stores",
        "key_files": "nuxt.config.ts, app.vue, pages/index.vue, server/api/hello.ts, stores/user.ts",
        "dependencies": "nuxt, vue, pinia, @pinia/nuxt, tailwindcss, typescript",
        "patterns": "composition API, auto-imports, server routes, middleware, state management, SSR",
        "use_cases": "content sites, dashboards, e-commerce, blogs, documentation sites",
        "complexity": "medium",
    },
    {
        "name": "Static Landing Page",
        "category": "Frontend",
        "subcategory": "Static",
        "tech_stack": "HTML5, CSS3, JavaScript, Tailwind CSS CDN",
        "description": "Responsive landing page with hero section, features grid, testimonials, pricing cards, CTA sections, and mobile-first design. No build step needed.",
        "folder_structure": "index.html, css/styles.css, js/main.js, images/",
        "key_files": "index.html, css/styles.css, js/main.js",
        "dependencies": "tailwindcss (CDN), alpinejs (optional)",
        "patterns": "responsive grid, intersection observer animations, smooth scrolling, mobile hamburger menu, dark mode toggle",
        "use_cases": "product launches, startup landing pages, event pages, waitlist pages, portfolio sites",
        "complexity": "low",
    },
    # ── Backend / API ──
    {
        "name": "FastAPI REST API",
        "category": "Backend",
        "subcategory": "Python",
        "tech_stack": "FastAPI, Python, SQLAlchemy, Pydantic, Alembic, PostgreSQL",
        "description": "Production-ready REST API with FastAPI, async SQLAlchemy ORM, Pydantic validation, JWT authentication, Alembic migrations, CORS, and OpenAPI docs.",
        "folder_structure": "app/api/routes, app/models, app/schemas, app/services, app/core, alembic/versions",
        "key_files": "app/main.py, app/core/config.py, app/core/database.py, app/api/routes/*.py, app/models/*.py, alembic.ini",
        "dependencies": "fastapi, uvicorn, sqlalchemy, alembic, pydantic, python-jose, passlib, asyncpg",
        "patterns": "dependency injection, repository pattern, async/await, middleware, background tasks, WebSocket",
        "use_cases": "REST APIs, microservices, real-time backends, data processing APIs, ML model serving",
        "complexity": "medium",
    },
    {
        "name": "Express.js + TypeScript API",
        "category": "Backend",
        "subcategory": "Node.js",
        "tech_stack": "Express, TypeScript, Prisma, Zod, JWT, PostgreSQL",
        "description": "Node.js REST API with Express, TypeScript, Prisma ORM, Zod request validation, JWT auth with refresh tokens, error middleware, and rate limiting.",
        "folder_structure": "src/routes, src/controllers, src/services, src/middleware, src/prisma, src/utils",
        "key_files": "src/index.ts, src/routes/index.ts, prisma/schema.prisma, src/middleware/auth.ts, tsconfig.json",
        "dependencies": "express, typescript, prisma, @prisma/client, zod, jsonwebtoken, bcrypt, helmet, cors",
        "patterns": "controller-service pattern, middleware chain, error handling middleware, request validation, rate limiting",
        "use_cases": "REST APIs, GraphQL servers, real-time apps with Socket.io, BFF (backend for frontend)",
        "complexity": "medium",
    },
    {
        "name": "Django REST Framework API",
        "category": "Backend",
        "subcategory": "Python",
        "tech_stack": "Django, DRF, PostgreSQL, Celery, Redis, JWT",
        "description": "Django REST Framework API with serializers, viewsets, token authentication, Celery async tasks, Redis caching, admin panel, and Django ORM migrations.",
        "folder_structure": "apps/<app>/models.py, apps/<app>/views.py, apps/<app>/serializers.py, apps/<app>/urls.py, config/",
        "key_files": "manage.py, config/settings.py, config/urls.py, apps/users/models.py, apps/users/views.py",
        "dependencies": "django, djangorestframework, celery, redis, django-cors-headers, djangorestframework-simplejwt, psycopg2",
        "patterns": "viewsets + routers, serializer validation, permissions, filtering, pagination, signals, celery tasks",
        "use_cases": "content management APIs, e-commerce backends, multi-tenant SaaS, admin-heavy apps",
        "complexity": "medium",
    },
    {
        "name": "Flask Microservice",
        "category": "Backend",
        "subcategory": "Python",
        "tech_stack": "Flask, SQLAlchemy, Marshmallow, Gunicorn, Docker",
        "description": "Lightweight Flask microservice with SQLAlchemy, Marshmallow serialization, Blueprint routing, health checks, and Docker containerization.",
        "folder_structure": "app/__init__.py, app/routes, app/models, app/schemas, app/services, Dockerfile",
        "key_files": "app/__init__.py, app/routes/api.py, app/models/user.py, Dockerfile, docker-compose.yml, requirements.txt",
        "dependencies": "flask, sqlalchemy, marshmallow, gunicorn, flask-cors, flask-migrate",
        "patterns": "application factory, blueprints, service layer, health endpoint, docker multi-stage build",
        "use_cases": "microservices, lightweight APIs, webhook handlers, internal tools, ML model wrappers",
        "complexity": "low",
    },
    {
        "name": "Spring Boot REST API",
        "category": "Backend",
        "subcategory": "Java",
        "tech_stack": "Spring Boot, Java 17, JPA/Hibernate, PostgreSQL, Maven, Spring Security",
        "description": "Enterprise Java REST API with Spring Boot, JPA entities, repository pattern, Spring Security with JWT, validation, exception handling, and Swagger docs.",
        "folder_structure": "src/main/java/com/app/controller, /service, /repository, /model, /config, /dto",
        "key_files": "Application.java, pom.xml, application.yml, SecurityConfig.java, UserController.java",
        "dependencies": "spring-boot-starter-web, spring-boot-starter-data-jpa, spring-boot-starter-security, springdoc-openapi, lombok",
        "patterns": "controller-service-repository, DTO mapping, global exception handler, specification pattern, pagination",
        "use_cases": "enterprise APIs, banking systems, ERP backends, government systems, large-scale services",
        "complexity": "high",
    },
    {
        "name": "Go Fiber REST API",
        "category": "Backend",
        "subcategory": "Go",
        "tech_stack": "Go, Fiber, GORM, PostgreSQL, JWT, Air (hot reload)",
        "description": "High-performance Go API with Fiber framework, GORM for database, JWT middleware, structured logging, and graceful shutdown.",
        "folder_structure": "cmd/server, internal/handler, internal/model, internal/repository, internal/middleware, pkg/",
        "key_files": "cmd/server/main.go, internal/handler/user.go, internal/model/user.go, go.mod, Makefile",
        "dependencies": "gofiber/fiber, gorm, golang-jwt, zap logger, viper config",
        "patterns": "clean architecture, handler-service-repository, middleware chain, structured errors, graceful shutdown",
        "use_cases": "high-throughput APIs, microservices, real-time systems, IoT backends, WebSocket servers",
        "complexity": "medium",
    },
    # ── Full-Stack ──
    {
        "name": "MERN Stack (Mongo + Express + React + Node)",
        "category": "Full-Stack",
        "subcategory": "MERN",
        "tech_stack": "MongoDB, Express.js, React, Node.js, TypeScript, Mongoose",
        "description": "Full-stack MERN application with separate client/server directories, Mongoose ODM, React frontend with Axios, JWT auth flow, and shared TypeScript types.",
        "folder_structure": "client/src/components, client/src/pages, server/routes, server/models, server/controllers, shared/types",
        "key_files": "server/index.ts, server/models/User.ts, client/src/App.tsx, client/src/api/index.ts, docker-compose.yml",
        "dependencies": "express, mongoose, react, axios, jsonwebtoken, bcryptjs, cors, dotenv",
        "patterns": "REST API + SPA, JWT auth flow, Mongoose schemas, React context, protected routes, file upload",
        "use_cases": "social networks, project management tools, content platforms, marketplace apps",
        "complexity": "high",
    },
    {
        "name": "T3 Stack (Next.js + tRPC + Prisma + NextAuth)",
        "category": "Full-Stack",
        "subcategory": "T3",
        "tech_stack": "Next.js, tRPC, Prisma, NextAuth.js, Tailwind CSS, TypeScript",
        "description": "Type-safe full-stack app with tRPC for end-to-end typesafe APIs, Prisma ORM, NextAuth for authentication, and Tailwind for styling. Zero API boilerplate.",
        "folder_structure": "src/server/api/routers, src/server/db, src/pages, src/components, prisma/",
        "key_files": "src/server/api/root.ts, src/server/api/routers/example.ts, prisma/schema.prisma, src/env.mjs",
        "dependencies": "next, @trpc/server, @trpc/client, prisma, next-auth, tailwindcss, zod",
        "patterns": "tRPC routers + procedures, Prisma schema, NextAuth providers, Zod validation, optimistic updates",
        "use_cases": "SaaS products, internal dashboards, CRUD apps, admin panels, prototypes",
        "complexity": "medium",
    },
    {
        "name": "Next.js + Supabase Full-Stack",
        "category": "Full-Stack",
        "subcategory": "Supabase",
        "tech_stack": "Next.js, Supabase, TypeScript, Tailwind CSS, Row Level Security",
        "description": "Full-stack app using Supabase as backend-as-a-service. Includes Supabase Auth, real-time subscriptions, storage for file uploads, and Row Level Security policies.",
        "folder_structure": "app/(auth), app/(dashboard), components, lib/supabase, supabase/migrations",
        "key_files": "lib/supabase/client.ts, lib/supabase/server.ts, supabase/migrations/*.sql, middleware.ts",
        "dependencies": "next, @supabase/supabase-js, @supabase/ssr, tailwindcss, typescript",
        "patterns": "server-side Supabase client, RLS policies, real-time subscriptions, storage buckets, edge functions",
        "use_cases": "SaaS apps, social apps, real-time dashboards, file-sharing apps, collaborative tools",
        "complexity": "medium",
    },
    {
        "name": "Next.js + Firebase Full-Stack",
        "category": "Full-Stack",
        "subcategory": "Firebase",
        "tech_stack": "Next.js, Firebase, TypeScript, Firestore, Firebase Auth, Cloud Functions",
        "description": "Full-stack app with Firebase services. Firestore for NoSQL database, Firebase Auth, Cloud Storage, Cloud Functions for serverless backend, and Firebase Hosting.",
        "folder_structure": "app/(routes), lib/firebase, functions/src, components, public",
        "key_files": "lib/firebase/config.ts, lib/firebase/auth.ts, functions/src/index.ts, firebase.json, firestore.rules",
        "dependencies": "next, firebase, firebase-admin, firebase-functions, tailwindcss",
        "patterns": "Firestore collections + documents, security rules, cloud functions triggers, auth state listener, real-time listeners",
        "use_cases": "real-time apps, chat apps, social platforms, notification systems, MVP prototypes",
        "complexity": "medium",
    },
    # ── DevOps / Infra ──
    {
        "name": "Docker + Docker Compose Setup",
        "category": "DevOps",
        "subcategory": "Docker",
        "tech_stack": "Docker, Docker Compose, Nginx, Let's Encrypt",
        "description": "Production Docker setup with multi-stage builds, Docker Compose for service orchestration, Nginx reverse proxy, SSL with Let's Encrypt, and health checks.",
        "folder_structure": "docker/, nginx/conf.d, scripts/, .dockerignore",
        "key_files": "Dockerfile, docker-compose.yml, docker-compose.prod.yml, nginx/conf.d/app.conf, .env.example",
        "dependencies": "docker, docker-compose, nginx, certbot",
        "patterns": "multi-stage builds, named volumes, health checks, env file injection, log rotation, zero-downtime deploy",
        "use_cases": "any web app deployment, microservice orchestration, CI/CD pipelines, local dev environments",
        "complexity": "medium",
    },
    {
        "name": "GitHub Actions CI/CD Pipeline",
        "category": "DevOps",
        "subcategory": "CI/CD",
        "tech_stack": "GitHub Actions, Docker, Node.js/Python, PostgreSQL service",
        "description": "CI/CD pipeline with lint, test, build, and deploy stages. Includes matrix testing, caching, artifact uploads, environment-based deployments, and Slack notifications.",
        "folder_structure": ".github/workflows, scripts/",
        "key_files": ".github/workflows/ci.yml, .github/workflows/deploy.yml, .github/workflows/release.yml",
        "dependencies": "github actions runners, docker, node/python, postgres service container",
        "patterns": "matrix strategy, dependency caching, environment secrets, reusable workflows, concurrency groups",
        "use_cases": "automated testing, continuous deployment, release automation, PR checks",
        "complexity": "medium",
    },
    # ── AI / ML ──
    {
        "name": "LangChain RAG Chatbot",
        "category": "AI",
        "subcategory": "LangChain",
        "tech_stack": "Python, LangChain, OpenAI, ChromaDB, FastAPI, Streamlit",
        "description": "RAG (Retrieval-Augmented Generation) chatbot with document ingestion, vector embeddings, semantic search, conversation memory, and streaming responses.",
        "folder_structure": "app/chains, app/vectorstore, app/ingest, app/api, data/documents",
        "key_files": "app/chains/rag_chain.py, app/vectorstore/chroma.py, app/ingest/loader.py, app/api/chat.py",
        "dependencies": "langchain, openai, chromadb, tiktoken, fastapi, streamlit, python-dotenv",
        "patterns": "retrieval chain, document splitting, embedding + vector store, conversation buffer memory, streaming callbacks",
        "use_cases": "customer support bots, knowledge base Q&A, document analysis, research assistants",
        "complexity": "high",
    },
    {
        "name": "AI Agent with Tool Use",
        "category": "AI",
        "subcategory": "Agents",
        "tech_stack": "Python, OpenAI/Anthropic, LangGraph, Tool calling, FastAPI",
        "description": "AI agent with function/tool calling capabilities. Includes tool definitions, execution loop, error handling, multi-step reasoning, and conversation persistence.",
        "folder_structure": "app/agents, app/tools, app/prompts, app/api, app/memory",
        "key_files": "app/agents/agent.py, app/tools/web_search.py, app/tools/calculator.py, app/prompts/system.py",
        "dependencies": "openai, anthropic, langgraph, tavily-python, fastapi, pydantic",
        "patterns": "ReAct loop, tool definition + execution, multi-agent orchestration, state graph, checkpointing",
        "use_cases": "autonomous agents, research assistants, code generators, data analysis agents, workflow automation",
        "complexity": "high",
    },
    # ── Data / Analytics ──
    {
        "name": "Python Data Pipeline (ETL)",
        "category": "Data",
        "subcategory": "ETL",
        "tech_stack": "Python, Pandas, SQLAlchemy, Apache Airflow, PostgreSQL",
        "description": "Data pipeline with extract-transform-load stages, scheduled via Airflow DAGs, data validation, incremental loading, and monitoring dashboards.",
        "folder_structure": "dags/, plugins/, scripts/, sql/, tests/, config/",
        "key_files": "dags/etl_pipeline.py, scripts/extract.py, scripts/transform.py, scripts/load.py, config/connections.yml",
        "dependencies": "pandas, sqlalchemy, apache-airflow, great-expectations, psycopg2, boto3",
        "patterns": "DAG orchestration, idempotent tasks, backfill support, data quality checks, partitioned processing",
        "use_cases": "data warehousing, analytics pipelines, report generation, data migration, log processing",
        "complexity": "high",
    },
    {
        "name": "Real-time Analytics Dashboard",
        "category": "Full-Stack",
        "subcategory": "Analytics",
        "tech_stack": "Next.js, D3.js/Recharts, WebSocket, FastAPI, TimescaleDB",
        "description": "Real-time analytics dashboard with live-updating charts, time-series data, filtering, date range selection, CSV export, and responsive card layouts.",
        "folder_structure": "frontend/components/charts, frontend/hooks, backend/app/api, backend/app/models",
        "key_files": "components/charts/LineChart.tsx, components/Dashboard.tsx, hooks/useWebSocket.ts, api/metrics.py",
        "dependencies": "next, recharts, d3, socket.io-client, fastapi, timescaledb, pandas",
        "patterns": "WebSocket data streaming, time-series aggregation, chart composition, responsive grid, export functionality",
        "use_cases": "business intelligence, IoT monitoring, financial dashboards, server monitoring, social media analytics",
        "complexity": "high",
    },
    # ── E-Commerce ──
    {
        "name": "E-Commerce Store (Next.js + Stripe)",
        "category": "Full-Stack",
        "subcategory": "E-Commerce",
        "tech_stack": "Next.js, Stripe, Prisma, NextAuth, Tailwind CSS, PostgreSQL",
        "description": "Complete e-commerce store with product catalog, cart, Stripe checkout, order management, user accounts, admin dashboard, and inventory tracking.",
        "folder_structure": "app/(store), app/(admin), app/api/webhooks, components/product, components/cart, lib/stripe",
        "key_files": "lib/stripe.ts, app/api/webhooks/stripe/route.ts, components/cart/CartProvider.tsx, prisma/schema.prisma",
        "dependencies": "next, stripe, @stripe/stripe-js, prisma, next-auth, tailwindcss, resend",
        "patterns": "Stripe Checkout, webhook handling, cart context, optimistic UI, admin RBAC, inventory management",
        "use_cases": "online stores, marketplace platforms, subscription boxes, digital product sales",
        "complexity": "high",
    },
    # ── Chat / Real-time ──
    {
        "name": "Real-time Chat App (WebSocket)",
        "category": "Full-Stack",
        "subcategory": "Chat",
        "tech_stack": "Next.js, Socket.io, Express, MongoDB, TypeScript",
        "description": "Real-time chat application with WebSocket connections, rooms/channels, typing indicators, online presence, message history, and file sharing.",
        "folder_structure": "client/components/chat, client/hooks, server/socket, server/models, server/routes",
        "key_files": "server/socket/handlers.ts, client/hooks/useSocket.ts, client/components/chat/ChatRoom.tsx, server/models/Message.ts",
        "dependencies": "socket.io, socket.io-client, express, mongoose, next, multer, sharp",
        "patterns": "socket rooms, event-driven messaging, presence tracking, typing indicators, message pagination, file upload",
        "use_cases": "team chat, customer support chat, social messaging, live collaboration, gaming chat",
        "complexity": "high",
    },
    # ── Auth ──
    {
        "name": "Authentication System (NextAuth + Prisma)",
        "category": "Full-Stack",
        "subcategory": "Auth",
        "tech_stack": "NextAuth.js, Prisma, PostgreSQL, Next.js, bcrypt, TOTP",
        "description": "Complete auth system with email/password, OAuth (Google/GitHub), magic links, 2FA (TOTP), session management, role-based access, and password reset flow.",
        "folder_structure": "app/api/auth, app/(auth)/login, app/(auth)/register, lib/auth, prisma/",
        "key_files": "lib/auth/options.ts, app/api/auth/[...nextauth]/route.ts, prisma/schema.prisma, middleware.ts",
        "dependencies": "next-auth, prisma, bcryptjs, otpauth, nodemailer, next, zod",
        "patterns": "OAuth providers, credential provider, session strategy, middleware protection, RBAC, 2FA enrollment",
        "use_cases": "any app needing user authentication, SaaS, multi-tenant apps, admin panels",
        "complexity": "medium",
    },
    # ── UI Component Libraries ──
    {
        "name": "shadcn/ui Component Library",
        "category": "UI Library",
        "subcategory": "Components",
        "tech_stack": "React, Radix UI, Tailwind CSS, TypeScript, Next.js, Vite",
        "description": "Beautifully designed, accessible, customizable components built on Radix UI primitives and styled with Tailwind CSS. Copy-paste into your project — not a traditional npm dependency.",
        "folder_structure": "components/ui/button.tsx, components/ui/dialog.tsx, components/ui/input.tsx, components/ui/card.tsx, lib/utils.ts",
        "key_files": "components.json, components/ui/*.tsx, lib/utils.ts, tailwind.config.ts",
        "dependencies": "tailwindcss, @radix-ui/react-dialog, @radix-ui/react-dropdown-menu, @radix-ui/react-slot, class-variance-authority, clsx, tailwind-merge, lucide-react",
        "patterns": "copy-paste components, variant props via CVA, compound components, accessible by default, theme tokens, dark mode, form integration with react-hook-form + zod",
        "use_cases": "SaaS dashboards, admin panels, product UIs, data tables, forms, settings pages, any serious React app",
        "complexity": "low",
    },
    {
        "name": "Magic UI — Animated Components",
        "category": "UI Library",
        "subcategory": "Landing Page",
        "tech_stack": "React, Next.js, TypeScript, Tailwind CSS, Framer Motion, shadcn-ui",
        "description": "Animated React components for design engineers. Copy-paste animated sections: hero, features grid, pricing cards, logo clouds, testimonials, bento grids, marquees, and more. 22k+ GitHub stars.",
        "folder_structure": "registry/magicui/*, components/sections/*, app/(docs)/*",
        "key_files": "registry/magicui/animated-beam.tsx, registry/magicui/bento-grid.tsx, registry/magicui/marquee.tsx, registry/magicui/dock.tsx",
        "dependencies": "framer-motion, tailwindcss, @radix-ui/react-*, class-variance-authority, clsx, lucide-react",
        "patterns": "animated hero sections, bento grid layouts, marquee scrolling, animated beams, dock navigation, globe visualization, shimmer buttons, typing animation, number ticker, orbit animation",
        "use_cases": "startup landing pages, SaaS marketing sites, product launches, portfolio showcases, agency websites, impressive hero sections",
        "complexity": "low",
    },
    {
        "name": "Aceternity UI — Modern Landing Components",
        "category": "UI Library",
        "subcategory": "Landing Page",
        "tech_stack": "React, Next.js, TypeScript, Tailwind CSS, Framer Motion",
        "description": "Modern animated UI components for stunning landing pages. Spotlight effects, 3D card transforms, background beams, meteor effects, infinite moving cards, parallax scroll, wavy backgrounds, and text generate effects.",
        "folder_structure": "components/ui/*, components/sections/*",
        "key_files": "components/ui/spotlight.tsx, components/ui/3d-card.tsx, components/ui/background-beams.tsx, components/ui/text-generate-effect.tsx",
        "dependencies": "framer-motion, tailwindcss, clsx, tailwind-merge",
        "patterns": "spotlight hover effects, 3D card transforms, background beams/grids, meteor animations, parallax scroll, text reveal animations, infinite scroll cards, wavy/aurora backgrounds, sticky scroll sections",
        "use_cases": "modern startup landing pages, impressive portfolio sites, product showcases, agency websites, dark-themed marketing sites",
        "complexity": "low",
    },
    # ── 3D / Interactive (React Three Fiber ecosystem) ──
    {
        "name": "React Three Fiber (R3F) — 3D in React",
        "category": "3D Interactive",
        "subcategory": "React Three Fiber",
        "tech_stack": "React, Three.js, @react-three/fiber, TypeScript",
        "description": "React renderer for Three.js. Build 3D scenes declaratively with JSX. Full Three.js compatibility, automatic disposal, event system (onClick, onPointerOver), and render loop hook. No performance overhead — outperforms vanilla Three.js at scale.",
        "folder_structure": "src/components/Scene.tsx, src/components/Model.tsx, src/App.tsx",
        "key_files": "src/App.tsx (Canvas wrapper), src/components/Scene.tsx, vite.config.ts or next.config.ts",
        "dependencies": "@react-three/fiber, three, @types/three, react, react-dom",
        "patterns": "Canvas component, useFrame render loop, useThree scene access, declarative mesh/light/camera, event handling (onClick, onPointerOver), suspense loading, instanced rendering, custom shaders",
        "use_cases": "interactive 3D websites, product configurators, data visualization, 3D portfolios, games, real estate walkthroughs, avatar builders, AI-powered 3D environments, CAD viewers",
        "complexity": "high",
    },
    {
        "name": "Drei — R3F Helper Components",
        "category": "3D Interactive",
        "subcategory": "React Three Fiber",
        "tech_stack": "React, @react-three/drei, @react-three/fiber, Three.js",
        "description": "Growing collection of ready-made abstractions for React Three Fiber. Cameras, controls, shapes, materials, loaders, effects, staging, and performance tools. Eliminates boilerplate for common 3D patterns.",
        "folder_structure": "src/components/3d/*, src/hooks/*",
        "key_files": "src/components/Scene.tsx (uses Drei components)",
        "dependencies": "@react-three/drei, @react-three/fiber, three",
        "patterns": "OrbitControls, ScrollControls, Environment/Sky/Cloud staging, useGLTF model loading, useTexture, Html overlay in 3D, Text/Text3D, MeshReflectorMaterial, ContactShadows, Instances for performance, RenderTexture, MeshPortalMaterial, Float/Billboard animations",
        "use_cases": "any R3F project, 3D product viewers, immersive scrolling experiences, 3D text overlays, model showcase, environment setup, physics-ready scenes",
        "complexity": "medium",
    },
    {
        "name": "React Three Rapier — 3D Physics",
        "category": "3D Interactive",
        "subcategory": "Physics",
        "tech_stack": "React, @react-three/rapier, @react-three/fiber, Rapier WASM, Three.js",
        "description": "React wrapper for Rapier WASM physics engine. Add physics to R3F scenes with RigidBody, colliders, joints, sensors, and debug visualization. Fast simulation with minimal overhead.",
        "folder_structure": "src/components/physics/*, src/components/3d/*",
        "key_files": "src/components/PhysicsScene.tsx",
        "dependencies": "@react-three/rapier, @react-three/fiber, @react-three/drei, three",
        "patterns": "Physics provider, RigidBody (dynamic/fixed/kinematic), CuboidCollider, BallCollider, MeshCollider, useFixedJoint, useRevoluteJoint, useSpringJoint, collision events (onCollisionEnter), sensor triggers, debug wireframes, instanced physics",
        "use_cases": "3D games, interactive physics demos, product drop simulations, marble runs, vehicle physics, ragdoll characters, bowling/billiards games",
        "complexity": "high",
    },
    {
        "name": "Theatre.js — Cinematic Motion Design",
        "category": "3D Interactive",
        "subcategory": "Animation",
        "tech_stack": "React, @theatre/core, @theatre/studio, @theatre/r3f, Three.js",
        "description": "Motion design editor for the web. Visual timeline editor for animating Three.js objects, HTML/SVG, and any JavaScript value. Studio GUI for keyframing with programmatic playback. Cinematic-grade animation control.",
        "folder_structure": "src/theatre/project.ts, src/components/AnimatedScene.tsx",
        "key_files": "src/theatre/project.ts (Theatre project + sheets), src/components/AnimatedScene.tsx",
        "dependencies": "@theatre/core, @theatre/studio, @theatre/r3f, @react-three/fiber, three",
        "patterns": "project + sheet + object model, visual keyframe editor, sequence playback, R3F integration via editable components, export animation state JSON, programmatic + visual hybrid workflow",
        "use_cases": "cinematic website intros, product reveal animations, storytelling sequences, interactive art installations, precise animation choreography, 3D scene transitions",
        "complexity": "high",
    },
    # ── Animation Libraries ──
    {
        "name": "GSAP — GreenSock Animation Platform",
        "category": "Animation",
        "subcategory": "JavaScript",
        "tech_stack": "JavaScript, GSAP, ScrollTrigger, React/Vue/vanilla",
        "description": "Industry-standard animation library used on 12M+ sites. Animates CSS, SVG, Canvas, WebGL, colors, strings, motion paths. Up to 20x faster than jQuery. Zero dependencies. Framework-agnostic — works with React, Vue, vanilla JS.",
        "folder_structure": "src/animations/*, src/hooks/useGsap.ts",
        "key_files": "src/animations/hero.ts, src/hooks/useGsap.ts",
        "dependencies": "gsap, @gsap/react (for React)",
        "patterns": "gsap.to/from/fromTo tweens, gsap.timeline() sequencing, ScrollTrigger (scroll-based animations), ScrollSmoother, SplitText (text animations), Draggable, Flip (layout transitions), MorphSVG, MotionPathPlugin, gsap.matchMedia() responsive animations, pinning sections",
        "use_cases": "scroll-driven animations, hero section reveals, text split animations, SVG morphing, parallax effects, page transitions, interactive storytelling, award-winning agency sites",
        "complexity": "medium",
    },
    {
        "name": "Motion (Framer Motion) — React Animation",
        "category": "Animation",
        "subcategory": "React",
        "tech_stack": "React, motion, TypeScript",
        "description": "Open-source animation library for React, JavaScript, and Vue. Declarative motion.div components with GPU-accelerated animations at 120fps. Springs, gestures, layout transitions, scroll-linked effects, and timelines. Batteries-included.",
        "folder_structure": "src/components/animated/*, src/hooks/*",
        "key_files": "src/components/animated/AnimatedCard.tsx, src/hooks/useMotion.ts",
        "dependencies": "motion (npm package, formerly framer-motion)",
        "patterns": "motion.div animate prop, variants for orchestrated animations, AnimatePresence for exit animations, useScroll + useTransform for scroll effects, layout animations, drag gestures, spring physics, whileHover/whileTap, stagger children",
        "use_cases": "React app animations, page transitions, modal/dialog animations, list reordering, scroll-triggered reveals, interactive cards, mobile gesture UIs, micro-interactions",
        "complexity": "low",
    },
    {
        "name": "Lenis — Smooth Scroll",
        "category": "Animation",
        "subcategory": "Scroll",
        "tech_stack": "JavaScript, lenis, React/Vue/vanilla",
        "description": "Lightweight smooth scroll library. Native browser scroll integration preserving sticky positioning, anchor links, and accessibility. Supports vertical, horizontal, and nested scrolling. Framework adapters for React and Vue. Honors prefers-reduced-motion.",
        "folder_structure": "src/lib/lenis.ts, src/components/SmoothScroll.tsx",
        "key_files": "src/lib/lenis.ts (init), src/components/SmoothScroll.tsx (React wrapper)",
        "dependencies": "lenis, @studio-freight/lenis (legacy)",
        "patterns": "smooth scroll init, scroll velocity tracking, WebGL scroll sync, parallax effects, scroll snapping, infinite scroll, horizontal scroll sections, GSAP ScrollTrigger integration, React useLenis hook",
        "use_cases": "portfolio sites, agency websites, parallax landing pages, WebGL experiences, smooth scrolling SPAs, award-winning web experiences",
        "complexity": "low",
    },
    # ── 3D Starter Templates ──
    {
        "name": "React Three Vite Starter",
        "category": "Starter Template",
        "subcategory": "3D + Vite",
        "tech_stack": "React, Three.js, @react-three/fiber, @react-three/drei, Vite, React Router, Tailwind CSS, TypeScript",
        "description": "Starter template for 3D web apps with persistent Canvas across page navigation. Vite bundler, GLSL shader imports, React Router routing, and Tailwind styling. Lighthouse score 95, FCP 1.8s.",
        "folder_structure": "src/components, src/pages, src/shaders, src/models, public/models",
        "key_files": "src/App.tsx, src/components/Canvas.tsx, src/pages/Home.tsx, vite.config.ts, tsconfig.json",
        "dependencies": "@react-three/fiber, @react-three/drei, three, react-router-dom, tailwindcss, vite, @vitejs/plugin-react, vite-plugin-glsl",
        "patterns": "persistent 3D canvas across routes, GLSL shader imports, DOM + canvas hybrid pages, model loading with Suspense, responsive 3D viewport",
        "use_cases": "3D portfolio sites, interactive product pages, 3D landing pages with multiple routes, WebGL experiences",
        "complexity": "medium",
    },
    {
        "name": "3D Landing Page (Vite + R3F + Docker + K8s)",
        "category": "Starter Template",
        "subcategory": "3D + DevOps",
        "tech_stack": "React, TypeScript, Vite, @react-three/fiber, Emotion CSS-in-JS, Docker, Kubernetes, pnpm",
        "description": "Production 3D landing page with Blender models, Docker containerization, and Kubernetes deployment manifests. Demonstrates modern tooling: hot reload dev, production builds, multi-environment deploy.",
        "folder_structure": "src/components, src/assets/models, public, deploy/k8s, Dockerfile, Makefile",
        "key_files": "src/App.tsx, Dockerfile, deploy/k8s/deployment.yaml, Makefile, vite.config.ts",
        "dependencies": "@react-three/fiber, @react-three/drei, three, @emotion/react, @emotion/styled, vite, pnpm",
        "patterns": "Blender model import, Docker multi-stage build, Kubernetes manifests, Makefile automation, CSS-in-JS theming, 3D scene composition",
        "use_cases": "production 3D landing pages, containerized web apps, K8s-deployed interactive sites, DevOps-ready 3D projects",
        "complexity": "high",
    },
]


def init_template_table(conn: sqlite3.Connection):
    conn.execute("""
        CREATE TABLE IF NOT EXISTS code_templates (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT UNIQUE,
            category TEXT,
            subcategory TEXT,
            tech_stack TEXT,
            description TEXT,
            folder_structure TEXT,
            key_files TEXT,
            dependencies TEXT,
            patterns TEXT,
            use_cases TEXT,
            complexity TEXT
        )
    """)
    conn.execute("""
        CREATE VIRTUAL TABLE IF NOT EXISTS templates_fts
        USING fts5(name, tech_stack, description, patterns, use_cases, dependencies, category)
    """)
    conn.commit()


def index_templates(db_path: str = DB_PATH):
    conn = sqlite3.connect(db_path)
    conn.execute("PRAGMA journal_mode=WAL")
    init_template_table(conn)

    conn.execute("DELETE FROM code_templates")
    conn.execute("DELETE FROM templates_fts")

    for t in TEMPLATES:
        conn.execute(
            """INSERT INTO code_templates
               (name, category, subcategory, tech_stack, description, folder_structure,
                key_files, dependencies, patterns, use_cases, complexity)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
            (t["name"], t["category"], t["subcategory"], t["tech_stack"],
             t["description"], t["folder_structure"], t["key_files"],
             t["dependencies"], t["patterns"], t["use_cases"], t["complexity"]),
        )
        conn.execute(
            "INSERT INTO templates_fts (name, tech_stack, description, patterns, use_cases, dependencies, category) VALUES (?, ?, ?, ?, ?, ?, ?)",
            (t["name"], t["tech_stack"], t["description"], t["patterns"],
             t["use_cases"], t["dependencies"], t["category"]),
        )

    conn.commit()
    print(f"Indexed {len(TEMPLATES)} code templates into {db_path}")
    conn.close()


if __name__ == "__main__":
    db = sys.argv[sys.argv.index("--db") + 1] if "--db" in sys.argv else DB_PATH
    index_templates(db)
